#!/usr/bin/env python3
"""
基础化工 Spider - 基础化工行业数据爬虫
Generated by fd-scraw-harness batch generator

Target URLs (20 sources):
  - https://www.sci99.com/
  - http://www.cpcifa.org.cn/
  - https://www.czce.com.cn
  - https://www.dce.com.cn
  - http://www.stats.gov.cn/
  - https://www.oilchem.net/
  - http://www.mii.gov.cn/
  - http://www.ccin.com.cn/
  - http://www.ccia.org.cn/
  - https://www.wind.com.cn
  ... and 10 more
"""
from __future__ import annotations

import json
import logging
import sqlite3
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from scrapling import Fetcher, Selector

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)

DB_PATH = Path(__file__).parent / "data" / "spider.db"
JSON_PATH = Path(__file__).parent / "output" / "results.json"
URLS = [
    {"url": "https://www.sci99.com/", "title": "卓创资讯 - 化工行业数据", "score": 96},
    {"url": "http://www.cpcifa.org.cn/", "title": "中国石油和化学工业联合会", "score": 95},
    {"url": "https://www.czce.com.cn", "title": "郑州商品交易所", "score": 95},
    {"url": "https://www.dce.com.cn", "title": "大连商品交易所", "score": 95},
    {"url": "http://www.stats.gov.cn/", "title": "国家统计局", "score": 95},
    {"url": "https://www.oilchem.net/", "title": "隆众资讯", "score": 94},
    {"url": "http://www.mii.gov.cn/", "title": "工业和信息化部", "score": 92},
    {"url": "http://www.ccin.com.cn/", "title": "中国化工信息中心", "score": 92},
    {"url": "http://www.ccia.org.cn/", "title": "中国氯碱工业协会", "score": 90},
    {"url": "https://www.wind.com.cn", "title": "万得金融终端", "score": 90},
    {"url": "https://www.cncn.com.cn/", "title": "中国石油和化学工业联合会", "score": 90},
    {"url": "https://www.baiinfo.com/", "title": "百川盈孚", "score": 90},
    {"url": "http://www.cisia.org.cn/", "title": "中国无机盐工业协会", "score": 88},
    {"url": "https://www.chinamonitor.com.cn/", "title": "中国化工网", "score": 88},
    {"url": "https://www.stats.gov.cn/sj/zxfb/", "title": "国家统计局 - 化学工业统计", "score": 88},
    {"url": "http://www.cnfia.org.cn/", "title": "中国氮肥工业协会", "score": 85},
    {"url": "https://tushare.pro", "title": "Tushare Pro", "score": 85},
    {"url": "https://datacenter.org.cn/", "title": "中国化工信息中心", "score": 85},
    {"url": "https://www.chemnet.com.cn/", "title": "生意社化工频道", "score": 82},
    {"url": "https://www.molbase.cn", "title": "摩贝化学品网", "score": 80},
]

def init_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("""
        CREATE TABLE IF NOT EXISTS scraped_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT NOT NULL,
            title TEXT,
            content TEXT,
            raw_html TEXT,
            scraped_at TEXT NOT NULL,
            UNIQUE(url)
        )
    """)
    conn.commit()
    return conn

def fetch_page(url: str) -> dict | None:
    try:
        fetcher = Fetcher(auto_match=False)
        response = fetcher.get(url, timeout=30)
        if response.status != 200:
            logger.warning("HTTP %d for %s", response.status, url)
            return None
        return {"url": url, "html": response.html, "status": response.status}
    except Exception as e:
        logger.error("Fetch failed for %s: %s", url, e)
        return None

def extract_data(html: str, url: str) -> list[dict]:
    sel = Selector(html)
    items = []
    for table in sel.css("table"):
        rows = table.css("tr")
        headers = [th.text.strip() for th in rows[0].css("th")] if rows else []
        for row in rows[1:]:
            cells = [td.text.strip() for td in row.css("td")]
            if cells:
                items.append({"url": url, "headers": headers, "cells": cells})
    return items

def save_data(conn, url, title, content, raw_html):
    conn.execute("""
        INSERT OR REPLACE INTO scraped_data (url, title, content, raw_html, scraped_at)
        VALUES (?, ?, ?, ?, ?)
    """, (url, title or "", content or "", raw_html or "", datetime.now().isoformat()))
    conn.commit()

def main():
    logger.info("Starting chemicals spider with %d URLs", len(URLS))
    conn = init_db()
    all_results = []
    for i, u in enumerate(URLS, 1):
        logger.info("[%d/%d] Fetching: %s", i, len(URLS), u["url"])
        page = fetch_page(u["url"])
        if page:
            items = extract_data(page["html"], u["url"])
            content = json.dumps(items, ensure_ascii=False) if items else ""
            save_data(conn, u["url"], u.get("title", ""), content, page["html"][:5000])
            all_results.extend(items)
            logger.info("  -> Extracted %d items", len(items))
        time.sleep(2)
    conn.close()
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    logger.info("Done! %d total items saved to %s", len(all_results), JSON_PATH)

if __name__ == "__main__":
    main()
