#!/usr/bin/env python3
"""
有色金属 Spider - 有色金属行业数据爬虫
Generated by fd-scraw-harness batch generator

Target URLs (26 sources):
  - https://www.cnia.org.cn
  - https://www.lme.com
  - https://www.stats.gov.cn/
  - https://www.smm.cn
  - https://www.smm.cn/
  - https://www.shfe.com.cn
  - https://www.lme.com/
  - https://www.smm.cn/metal
  - https://www.chinametal.org.cn/
  - http://www.atkcn.com
  ... and 16 more
"""
from __future__ import annotations

import json
import logging
import sqlite3
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from scrapling import Fetcher, Selector

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)

DB_PATH = Path(__file__).parent / "data" / "spider.db"
JSON_PATH = Path(__file__).parent / "output" / "results.json"
URLS = [
    {"url": "https://www.cnia.org.cn", "title": "中国有色金属工业协会", "score": 95},
    {"url": "https://www.lme.com", "title": "LME London Metal Exchange", "score": 95},
    {"url": "https://www.stats.gov.cn/", "title": "国家统计局", "score": 95},
    {"url": "https://www.smm.cn", "title": "上海有色网 (SMM)", "score": 95},
    {"url": "https://www.smm.cn/", "title": "上海有色网 (SMM)", "score": 95},
    {"url": "https://www.shfe.com.cn", "title": "Shanghai Futures Exchange (SHFE)", "score": 92},
    {"url": "https://www.lme.com/", "title": "伦敦金属交易所 (LME)", "score": 92},
    {"url": "https://www.smm.cn/metal", "title": "上海有色网", "score": 90},
    {"url": "https://www.chinametal.org.cn/", "title": "中国有色金属工业协会", "score": 90},
    {"url": "http://www.atkcn.com", "title": "安泰科 (Antaike)", "score": 90},
    {"url": "https://data.stats.gov.cn", "title": "国家统计局-工业数据", "score": 88},
    {"url": "https://www.inmetals.com", "title": "S&P Global Commodity Insights (Metal Bulletin)", "score": 88},
    {"url": "https://www.fastmarkets.com/", "title": "Fastmarkets MB", "score": 88},
    {"url": "https://www.metal.com", "title": "我的钢铁网-有色金属频道", "score": 85},
    {"url": "https://www.kitco.com", "title": "Kitco Precious & Base Metals", "score": 85},
    {"url": "http://www.shfe.com.cn/", "title": "上海期货交易所", "score": 85},
    {"url": "http://www.shfe.com.cn", "title": "上海期货交易所 (SHFE)", "score": 85},
    {"url": "https://www.wind.com.cn/", "title": "万得金融终端 (Wind)", "score": 85},
    {"url": "https://www.wind.com.cn", "title": "万得金融终端-有色金属板块", "score": 82},
    {"url": "https://www.chinametal.com.cn", "title": "China Metal Market Network", "score": 82},
    {"url": "https://www.asianmetal.net/", "title": "Asian Metal", "score": 82},
    {"url": "https://www.wbms.org", "title": "World Bureau of Metal Statistics", "score": 80},
    {"url": "https://www.miit.gov.cn/", "title": "中华人民共和国工业和信息化部", "score": 80},
    {"url": "http://www.cnia.org.cn", "title": "中国有色金属工业协会", "score": 80},
    {"url": "https://www.cathayfutures.com", "title": "Cathay Futures Exchange Data", "score": 75},
    {"url": "https://www.baiinfo.com", "title": "百川盈孚", "score": 75},
]

def init_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("""
        CREATE TABLE IF NOT EXISTS scraped_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT NOT NULL,
            title TEXT,
            content TEXT,
            raw_html TEXT,
            scraped_at TEXT NOT NULL,
            UNIQUE(url)
        )
    """)
    conn.commit()
    return conn

def fetch_page(url: str) -> dict | None:
    try:
        fetcher = Fetcher(auto_match=False)
        response = fetcher.get(url, timeout=30)
        if response.status != 200:
            logger.warning("HTTP %d for %s", response.status, url)
            return None
        return {"url": url, "html": response.html, "status": response.status}
    except Exception as e:
        logger.error("Fetch failed for %s: %s", url, e)
        return None

def extract_data(html: str, url: str) -> list[dict]:
    sel = Selector(html)
    items = []
    for table in sel.css("table"):
        rows = table.css("tr")
        headers = [th.text.strip() for th in rows[0].css("th")] if rows else []
        for row in rows[1:]:
            cells = [td.text.strip() for td in row.css("td")]
            if cells:
                items.append({"url": url, "headers": headers, "cells": cells})
    return items

def save_data(conn, url, title, content, raw_html):
    conn.execute("""
        INSERT OR REPLACE INTO scraped_data (url, title, content, raw_html, scraped_at)
        VALUES (?, ?, ?, ?, ?)
    """, (url, title or "", content or "", raw_html or "", datetime.now().isoformat()))
    conn.commit()

def main():
    logger.info("Starting nonferrous spider with %d URLs", len(URLS))
    conn = init_db()
    all_results = []
    for i, u in enumerate(URLS, 1):
        logger.info("[%d/%d] Fetching: %s", i, len(URLS), u["url"])
        page = fetch_page(u["url"])
        if page:
            items = extract_data(page["html"], u["url"])
            content = json.dumps(items, ensure_ascii=False) if items else ""
            save_data(conn, u["url"], u.get("title", ""), content, page["html"][:5000])
            all_results.extend(items)
            logger.info("  -> Extracted %d items", len(items))
        time.sleep(2)
    conn.close()
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    logger.info("Done! %d total items saved to %s", len(all_results), JSON_PATH)

if __name__ == "__main__":
    main()
