#!/usr/bin/env python3
"""
农林牧渔 Spider - 农林牧渔行业数据爬虫
Generated by fd-scraw-harness batch generator

Target URLs (22 sources):
  - http://www.dce.com.cn
  - http://www.czce.com.cn
  - https://www.moa.gov.cn/
  - http://www.moa.gov.cn/
  - http://www.stats.gov.cn/sj/
  - http://www.stats.gov.cn/
  - https://www.cmegroup.com/markets/agricultural.html
  - https://www.stats.gov.cn/
  - http://www.caisi.org.cn/
  - http://www.moa.gov.cn/zwllm/
  ... and 12 more
"""
from __future__ import annotations

import json
import logging
import sqlite3
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from scrapling import Fetcher, Selector

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)

DB_PATH = Path(__file__).parent / "data" / "spider.db"
JSON_PATH = Path(__file__).parent / "output" / "results.json"
URLS = [
    {"url": "http://www.dce.com.cn", "title": "大连商品交易所", "score": 98},
    {"url": "http://www.czce.com.cn", "title": "郑州商品交易所", "score": 98},
    {"url": "https://www.moa.gov.cn/", "title": "中华人民共和国农业农村部", "score": 95},
    {"url": "http://www.moa.gov.cn/", "title": "中华人民共和国农业农村部", "score": 95},
    {"url": "http://www.stats.gov.cn/sj/", "title": "国家统计局数据查询", "score": 95},
    {"url": "http://www.stats.gov.cn/", "title": "国家统计局", "score": 92},
    {"url": "https://www.cmegroup.com/markets/agricultural.html", "title": "CME Group Agriculture", "score": 90},
    {"url": "https://www.stats.gov.cn/", "title": "国家统计局", "score": 90},
    {"url": "http://www.caisi.org.cn/", "title": "中国农业信息网", "score": 90},
    {"url": "http://www.moa.gov.cn/zwllm/", "title": "农业农村部政务信息", "score": 90},
    {"url": "http://www.caa.org.cn/", "title": "中国畜牧业协会", "score": 88},
    {"url": "https://data.eastmoney.com/futures/", "title": "东方财富期货数据中心", "score": 88},
    {"url": "https://data.stats.gov.cn/", "title": "国家数据数据库", "score": 88},
    {"url": "http://www.agri-info.cn/", "title": "中国农业信息网", "score": 88},
    {"url": "http://www.chinafisheries.org.cn/", "title": "中国渔业协会", "score": 85},
    {"url": "http://www.shfe.com.cn", "title": "上海期货交易所", "score": 85},
    {"url": "http://www.agrinet.gov.cn/", "title": "中国农业信息网", "score": 85},
    {"url": "http://www.chyxx.com/", "title": "中国产业研究网", "score": 85},
    {"url": "https://www.zce.com.cn/market/data.html", "title": "郑州商品交易所行情数据", "score": 85},
    {"url": "http://www.cfia.net.cn/", "title": "中国饲料工业协会", "score": 82},
    {"url": "https://www.huinong.com/", "title": "惠农网", "score": 82},
    {"url": "http://www.fao.org/faostat/en/#home", "title": "FAOSTAT 全球农业统计", "score": 75},
]

def init_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("""
        CREATE TABLE IF NOT EXISTS scraped_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT NOT NULL,
            title TEXT,
            content TEXT,
            raw_html TEXT,
            scraped_at TEXT NOT NULL,
            UNIQUE(url)
        )
    """)
    conn.commit()
    return conn

def fetch_page(url: str) -> dict | None:
    try:
        fetcher = Fetcher(auto_match=False)
        response = fetcher.get(url, timeout=30)
        if response.status != 200:
            logger.warning("HTTP %d for %s", response.status, url)
            return None
        return {"url": url, "html": response.html, "status": response.status}
    except Exception as e:
        logger.error("Fetch failed for %s: %s", url, e)
        return None

def extract_data(html: str, url: str) -> list[dict]:
    sel = Selector(html)
    items = []
    for table in sel.css("table"):
        rows = table.css("tr")
        headers = [th.text.strip() for th in rows[0].css("th")] if rows else []
        for row in rows[1:]:
            cells = [td.text.strip() for td in row.css("td")]
            if cells:
                items.append({"url": url, "headers": headers, "cells": cells})
    return items

def save_data(conn, url, title, content, raw_html):
    conn.execute("""
        INSERT OR REPLACE INTO scraped_data (url, title, content, raw_html, scraped_at)
        VALUES (?, ?, ?, ?, ?)
    """, (url, title or "", content or "", raw_html or "", datetime.now().isoformat()))
    conn.commit()

def main():
    logger.info("Starting agriculture spider with %d URLs", len(URLS))
    conn = init_db()
    all_results = []
    for i, u in enumerate(URLS, 1):
        logger.info("[%d/%d] Fetching: %s", i, len(URLS), u["url"])
        page = fetch_page(u["url"])
        if page:
            items = extract_data(page["html"], u["url"])
            content = json.dumps(items, ensure_ascii=False) if items else ""
            save_data(conn, u["url"], u.get("title", ""), content, page["html"][:5000])
            all_results.extend(items)
            logger.info("  -> Extracted %d items", len(items))
        time.sleep(2)
    conn.close()
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    logger.info("Done! %d total items saved to %s", len(all_results), JSON_PATH)

if __name__ == "__main__":
    main()
