#!/usr/bin/env python3
"""
证券业协会 Spider - 证券业协会行业数据爬虫
Generated by fd-scraw-harness batch generator

Target URLs (4 sources):
  - https://www.amac.org.cn/
  - https://www.sac.net.cn/
  - https://www.chinabankass.org.cn/
  - https://www.iachina.cn/
"""
from __future__ import annotations

import json
import logging
import sqlite3
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from scrapling import Fetcher, Selector

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)

DB_PATH = Path(__file__).parent / "data" / "spider.db"
JSON_PATH = Path(__file__).parent / "output" / "results.json"
URLS = [
    {"url": "https://www.amac.org.cn/", "title": "中国证券投资基金业协会 (AMAC)", "score": 98},
    {"url": "https://www.sac.net.cn/", "title": "中国证券业协会 (SAC)", "score": 95},
    {"url": "https://www.chinabankass.org.cn/", "title": "中国银行业协会 (CBA)", "score": 92},
    {"url": "https://www.iachina.cn/", "title": "中国保险行业协会 (IAC)", "score": 90},
]

def init_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("""
        CREATE TABLE IF NOT EXISTS scraped_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT NOT NULL,
            title TEXT,
            content TEXT,
            raw_html TEXT,
            scraped_at TEXT NOT NULL,
            UNIQUE(url)
        )
    """)
    conn.commit()
    return conn

def fetch_page(url: str) -> dict | None:
    try:
        fetcher = Fetcher(auto_match=False)
        response = fetcher.get(url, timeout=30)
        if response.status != 200:
            logger.warning("HTTP %d for %s", response.status, url)
            return None
        return {"url": url, "html": response.html, "status": response.status}
    except Exception as e:
        logger.error("Fetch failed for %s: %s", url, e)
        return None

def extract_data(html: str, url: str) -> list[dict]:
    sel = Selector(html)
    items = []
    for table in sel.css("table"):
        rows = table.css("tr")
        headers = [th.text.strip() for th in rows[0].css("th")] if rows else []
        for row in rows[1:]:
            cells = [td.text.strip() for td in row.css("td")]
            if cells:
                items.append({"url": url, "headers": headers, "cells": cells})
    return items

def save_data(conn, url, title, content, raw_html):
    conn.execute("""
        INSERT OR REPLACE INTO scraped_data (url, title, content, raw_html, scraped_at)
        VALUES (?, ?, ?, ?, ?)
    """, (url, title or "", content or "", raw_html or "", datetime.now().isoformat()))
    conn.commit()

def main():
    logger.info("Starting securities spider with %d URLs", len(URLS))
    conn = init_db()
    all_results = []
    for i, u in enumerate(URLS, 1):
        logger.info("[%d/%d] Fetching: %s", i, len(URLS), u["url"])
        page = fetch_page(u["url"])
        if page:
            items = extract_data(page["html"], u["url"])
            content = json.dumps(items, ensure_ascii=False) if items else ""
            save_data(conn, u["url"], u.get("title", ""), content, page["html"][:5000])
            all_results.extend(items)
            logger.info("  -> Extracted %d items", len(items))
        time.sleep(2)
    conn.close()
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    logger.info("Done! %d total items saved to %s", len(all_results), JSON_PATH)

if __name__ == "__main__":
    main()
