#!/usr/bin/env python3
"""
电子 Spider - 电子行业数据爬虫
Generated by fd-scraw-harness batch generator

Target URLs (22 sources):
  - http://www.ceia.org.cn
  - https://www.miit.gov.cn/
  - https://www.trendforce.com/
  - https://www.alphavantage.co/
  - https://data.fred.stlouisfed.org/
  - https://www.semi.org
  - https://polygon.io/
  - https://www.stats.gov.cn/
  - https://www.cinnoresearch.com/
  - https://www.intrinio.com/
  ... and 12 more
"""
from __future__ import annotations

import json
import logging
import sqlite3
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from scrapling import Fetcher, Selector

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)

DB_PATH = Path(__file__).parent / "data" / "spider.db"
JSON_PATH = Path(__file__).parent / "output" / "results.json"
URLS = [
    {"url": "http://www.ceia.org.cn", "title": "中国电子行业协会", "score": 95},
    {"url": "https://www.miit.gov.cn/", "title": "中华人民共和国工业和信息化部", "score": 95},
    {"url": "https://www.trendforce.com/", "title": "TrendForce Market Intelligence", "score": 95},
    {"url": "https://www.alphavantage.co/", "title": "Alpha Vantage", "score": 92},
    {"url": "https://data.fred.stlouisfed.org/", "title": "FRED Economic Data", "score": 91},
    {"url": "https://www.semi.org", "title": "SEMI - 国际半导体设备材料产业协会", "score": 90},
    {"url": "https://polygon.io/", "title": "Polygon.io Stock Market Data", "score": 90},
    {"url": "https://www.stats.gov.cn/", "title": "国家统计局", "score": 90},
    {"url": "https://www.cinnoresearch.com/", "title": "CINNO Research", "score": 90},
    {"url": "https://www.intrinio.com/", "title": "Intrinio Financial Data", "score": 89},
    {"url": "https://www.csia.net.cn", "title": "中国半导体行业协会", "score": 88},
    {"url": "https://data.worldbank.org/", "title": "World Bank Open Data", "score": 88},
    {"url": "https://www.ccidconsulting.com/", "title": "CCID Consulting", "score": 88},
    {"url": "https://coinmarketcap.com/api/", "title": "CoinMarketCap API", "score": 87},
    {"url": "https://www.sec.gov/edgar/searchedgar/companysearch.html", "title": "SEC EDGAR Database", "score": 86},
    {"url": "https://www.bls.gov/data/", "title": "Bureau of Labor Statistics", "score": 85},
    {"url": "https://www.caict.ac.cn/", "title": "中国信息通信研究院", "score": 85},
    {"url": "https://www.digitimes.com/research/", "title": "Digitimes Research", "score": 85},
    {"url": "https://www.gartner.com/en/insights/topics/electronics", "title": "Gartner电子行业分析", "score": 82},
    {"url": "https://www.ggii.cn/", "title": "GaoGong Industry Research", "score": 82},
    {"url": "https://www.ceia.org.cn/", "title": "中国电子企业联合会", "score": 80},
    {"url": "https://www.idc.com/getdoc.jsp?containerId=prCHC48709223", "title": "IDC中国电子产品追踪", "score": 78},
]

def init_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.execute("""
        CREATE TABLE IF NOT EXISTS scraped_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            url TEXT NOT NULL,
            title TEXT,
            content TEXT,
            raw_html TEXT,
            scraped_at TEXT NOT NULL,
            UNIQUE(url)
        )
    """)
    conn.commit()
    return conn

def fetch_page(url: str) -> dict | None:
    try:
        fetcher = Fetcher(auto_match=False)
        response = fetcher.get(url, timeout=30)
        if response.status != 200:
            logger.warning("HTTP %d for %s", response.status, url)
            return None
        return {"url": url, "html": response.html, "status": response.status}
    except Exception as e:
        logger.error("Fetch failed for %s: %s", url, e)
        return None

def extract_data(html: str, url: str) -> list[dict]:
    sel = Selector(html)
    items = []
    for table in sel.css("table"):
        rows = table.css("tr")
        headers = [th.text.strip() for th in rows[0].css("th")] if rows else []
        for row in rows[1:]:
            cells = [td.text.strip() for td in row.css("td")]
            if cells:
                items.append({"url": url, "headers": headers, "cells": cells})
    return items

def save_data(conn, url, title, content, raw_html):
    conn.execute("""
        INSERT OR REPLACE INTO scraped_data (url, title, content, raw_html, scraped_at)
        VALUES (?, ?, ?, ?, ?)
    """, (url, title or "", content or "", raw_html or "", datetime.now().isoformat()))
    conn.commit()

def main():
    logger.info("Starting electronics spider with %d URLs", len(URLS))
    conn = init_db()
    all_results = []
    for i, u in enumerate(URLS, 1):
        logger.info("[%d/%d] Fetching: %s", i, len(URLS), u["url"])
        page = fetch_page(u["url"])
        if page:
            items = extract_data(page["html"], u["url"])
            content = json.dumps(items, ensure_ascii=False) if items else ""
            save_data(conn, u["url"], u.get("title", ""), content, page["html"][:5000])
            all_results.extend(items)
            logger.info("  -> Extracted %d items", len(items))
        time.sleep(2)
    conn.close()
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    logger.info("Done! %d total items saved to %s", len(all_results), JSON_PATH)

if __name__ == "__main__":
    main()
